language: ruby
rvm:
- 2.2
script:
- bundle exec jekyll build
after_success:
- git config user.name "Travis CI"
- git config user.email ${EMAIL}
- git add -A
- git commit -m "Generated Jekyll site by Travis CI - ${TRAVIS_BUILD_NUMBER}"
- git push --force "https://${DEPLOY_KEY}@${GITHUB_REPO}" HEAD:${REPO_TARGET_BRANCH}
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GITHUB_REPO: github.com/AsherJia/AsherBlog.git
  - REPO_TARGET_BRANCH: gh-pages
  - secure: bw9wd0Y0vpDrX8Sq1uXVuQudbqN3uC5Xf/ruDRiauW/JpHqxwCwNY0W4r3G5wNMIOqqxTSv2L3sF5rZ7U2o88ohX6T+4VI43LyTEF2QhnGpJxQd9IQXIKCiit4l7zGmwaR00KwsCGc1SXm5Ovwzw48AzLpyMaFhkcFkgPwz/oMeSYm5Xj/VuSXl/QY60g0G2QkG/8dT42AYHbd+5eQ8S5qv2sxRk+IouDzE48CkL+0f7Yn5ws3VYk5p/7odKhL2lCpczruzf4H4YrlBIc/6tSd4z/jmREyQfIVY4ihIw9medySDfsNfYIQGhtx505KiN/13c9vuyX9ARQMZ/ow/Js4yh66aaN/2Piq0sCBmsYNsoEgaBC3y59+1ZGhHA+NxuGfE/h+NTtvQEwIh/87LUtjN7kyJXo81jR/KdobMkAm9EFf04/woR9y/YU5/If1rDkbEAG5Qk2yQiPIlaQLNgPCe49KD3U69I6S9qimQdNyroNu1+m7rVXG3ubOCQB2asFG63xlGixUnJAVFceGId06O4j3/kgkEeNQEU3UtmFDeQD8aAKFqAJCa4++SxA5o97byFvJbYYUvbIPd59jbtTKShXSNivQzGxv863ywExr0edhQ4eUcpOH9QGu3M9YFSTlQjE6GkskG6Jn2dLzfgh42R417fgRw5YvIEAKT4llk=
  - secure: NWR8R2O9fXlwChqVm//PYLoRbHVAj5JWA622EFi09vyrpP9tizOFPzDifvYv9FeueNl+YqGYCoARSl8EqhOxI8MaUzw4EIhltxTRvh+8EKFh1AZwSnh+vnmfjy8a22+BwBbJhzn0RbqFXqvH4jYtlR+W01tDHWAOV1nBLYGmOUqVPKzvd0zUb0bGGAjR1cm0PPHrA+b2Qo3L8zPAZ1KE0jpvBzQ6TPcUqeAa52tvsyGpKk158d0EBow7i2vGltOlx0HAyHlp8FyB3ypz0Oc2UIRcbthP3roYAgCYLr9aoJ8xc1qvg+XeHIvR6hAnaVseQ6EsyX4Bwxof1FjJPy5bslCcJ9gpjo2KGhBo89gptKM+VZHU2EOpiHTyJuFxM6uz9KhVbv+t+FIy8CIusHZ8nB97LfFf93dga0HmkEzSXj8I/APvcpmLxWcUX6ONqTRegqlBwFKNKvE5Qni6+bYrSAgmzcjwNugNVEPHBroisWWPghhIkvgqxj/Ccuxk4KuxzufYJ68Ala/kbxEbR59So5exj+XwB1E+QVpZvOcAdbmbo4ULPrxsEKGRzHJjlW49/VDr95RmAy0WevebDZlAUG7eF5vFpkwcU26+qOFO53sKxqWZbiWfpFQD9oJj6xEfr8+aRI17P2bHMFbU7LSxIs95mkRil7aK8kG1B7h/IiI=
